cambio

diff --git a/.github/workflows/tesCI.yml b/.github/workflows/tesCI.yml
--- a/.github/workflows/tesCI.yml
+++ b/.github/workflows/tesCI.yml
@@ -1,8 +1,60 @@
-josb:
-verificar_codigo:
-runs-on: ubuntu-latest
-steps:
-  - name: checkout repositorio
-    uses: actions/checkout@v4
-    -name: mostar archivo(opcional,para depurar)
-    run: ls -R
+name: CI & Despliegue a GitHub Pass
+
+on:
+  push:
+    branches: ["main", "frontend"]
+  pull_request:
+    branches: ["main"]
+  workflow_dispatch:
+
+concurrency:
+    group: "CI-CD-GHPages"
+    cancel-in-progress: true
+
+jobs:
+  verificar_codigo:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout del repositorio
+        uses: actions/checkout@v4
+
+      - name: Mostrar archivos (opcional para depurar)
+        run: ls -R
+
+      - name: verificar archivos principales
+        run: |
+          if [ -f index.html ] && [ -f index.css ]; then
+            echo "Archivos HTML y CSS encontrados." ¡CI Basico superado!
+          else
+            echo "Error: Faltan archivos index.html o index.css."
+            exit 1
+          fi
+
+  desplegar_paguina:
+    needs: verificar_codigo
+    if: github.ref == 'refs/heads/main' 
+    runs-on: ubuntu-latest
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+
+    permissions:
+      contents: read
+      pages: write
+      id-token: write 
+      
+    steps:
+      - name: Checkout del repositorio
+        uses: actions/checkout@v4
+
+      - name: Configurar GitHub Pages
+        uses: actions/configure-pages@v5
+
+      - name: Subir artifactos de despliegue
+        uses: actions/upload-pages-artifact@v3
+        with:
+          path: ./
+
+      - name: Iniciar Despliegue a Pages
+        id: deployment
+        uses: actions/deploy-pages@v4
